language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python3 -m unittest tests.test_DB
  - python3 -m unittest tests.test_CorruptedMonitorFileValidation
  - python3 -m unittest tests.test_ProducerEqualConsumer